<?php

declare(strict_types=1);

namespace Morscate\UberEats\Enums;

enum CancelType: string
{
    case ITEM_ISSUE = 'ITEM_ISSUE';
    case KITCHEN_CLOSED = 'KITCHEN_CLOSED';
    case CUSTOMER_CALLED_TO_CANCEL = 'CUSTOMER_CALLED_TO_CANCEL';
    case RESTAURANT_TOO_BUSY = 'RESTAURANT_TOO_BUSY';
    case ORDER_VALIDATION = 'ORDER_VALIDATION';
    case STORE_CLOSED = 'STORE_CLOSED';
    case TECHNICAL_FAILURE = 'TECHNICAL_FAILURE';
    case POS_NOT_READY = 'POS_NOT_READY';
    case POS_OFFLINE = 'POS_OFFLINE';
    case CAPACITY = 'CAPACITY';
    case ADDRESS = 'ADDRESS';
    case SPECIAL_INSTRUCTIONS = 'SPECIAL_INSTRUCTIONS';
    case PRICING = 'PRICING';
    case UNKNOWN = 'UNKNOWN';
    case OTHER = 'OTHER';
}
